fix issue and missing words
DCC-org/rna_documentation pull request #11
Opened 2018-04-15 11:25 UTC by Marcellii

Regarding Issue #9

2018-04-15 11:28 UTC, bastelfreak commented
Fixes https://github.com/DCC-org/rna_documentation/issues/9

2018-04-15 11:58 UTC, bastelfreak requested changes

2018-04-15 11:58 UTC, bastelfreak commented on content.tex
> +Server weitergeben werden. Die Auflösungder IP Adresse des Dom\"änen
da fehlt ein leerzeichen zwischen `Auflösung` und `der`

ö als umlaut: `\"o`
ä als umlaut: `\"a`

2018-04-15 11:58 UTC, bastelfreak commented on content.tex
>  W16dc01.mikado.spiel
fehlt dann da nicht die IP-Adresse?

2018-04-15 12:03 UTC, Marcellii commented
if needed, we can add the administration network in the table.

2018-04-15 14:08 UTC, bastelfreak requested changes

2018-04-15 14:08 UTC, bastelfreak commented on content.tex
> +Dom\"änen Controllers, w\"are bei diesem Server dann wie folgt:
Da ist immernoch ein ä

2018-04-17 19:40 UTC, bastelfreak approved these changes

2018-04-17 19:41 UTC, merged